name: Retry Failed Transfers

on:
  schedule:
    - cron: '0 * * * *' # Every hour at minute 0
  workflow_dispatch: # Allow manual trigger

jobs:
  retry-transfers:
    runs-on: ubuntu-latest
    steps:
      - name: Retry Failed Transfers
        run: |
          response=$(curl -s -w "%{http_code}" -X POST \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
            -H "Content-Type: application/json" \
            "${{ secrets.SUPABASE_URL }}/functions/v1/process-pending-transfers" \
            -d '{}')

          http_code="${response: -3}"
          body="${response%???}"

          if [ "$http_code" -ne 200 ]; then
            echo "Error: HTTP $http_code"
            echo "$body"
            exit 1
          fi

          echo "Success: $body"
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

      - name: Notify on Failure
        if: failure()
        run: |
          echo "🚨 Failed transfer retry job failed!"
          # Add Slack/Discord/Email notification here if needed
